# Generated by Django 4.2.11 on 2025-07-02 13:48

from django.db import migrations, models
import main_ai.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleTransferResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.ImageField(upload_to=main_ai.models.get_upload_path)),
                ('style_image', models.ImageField(upload_to=main_ai.models.get_upload_path)),
                ('result_image', models.ImageField(upload_to='results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
